name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Build
        run: yarn
      - name: Check for uncommitted changes in yarn.lock
        run: |
          if git diff --name-only | grep -q "^yarn.lock"; then
            echo "::error::The yarn.lock file has uncommitted changes!"
            exit 1
          fi
      - name: ESLint Check
        run: yarn lint:ci
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@2.2.0
        with:
          report-json: 'eslint_report.json'
        if: always()
      - name: Tests (Mocha)
        run: yarn test:ci
      - name: Create test summary
        uses: test-summary/action@v2.3
        with:
          paths: ./**/*/report.xml
        if: always()
      - name: Test coverage (master only)
        if: github.ref == 'refs/heads/citest'
        run: yarn test:coverage:ci
      - name: Upload coverage report (master only)
        if: github.ref == 'refs/heads/citest'
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my_file.txt
          retention-days: 30
